#ifndef TIMEBASEDEFVAR
#define TIMEBASEDEFVAR


// Version 1.1
module TimeBase {



  // Time units100 nanoseconds (10-7 seconds)
  // Base time15 October 1582 00:00:00.
  // Approximate range AD 30,000
  // The corresponding binary representations of relative time is the same one as
  // for absolute time, and hence with similar characteristics:
  // Time units100 nanoseconds (10-7 seconds)
  // Approximate range+/- 30,000 years 
  typedef unsigned long long TimeT;
  



};
#endif